"""Reproducible R15: public boundary changes over immutable R14, engine/assets frozen."""
from __future__ import annotations

import ast
import hashlib
import io
import json
from pathlib import Path
import subprocess
import sys
import zipfile

ROOT = Path(__file__).resolve().parents[2]
BASE = "094745b26bc57aee5cc1a5e003401743d96a914f"
BASE_ZIP = "scripts/vnext_agent/dist/r14/gipuzkoa360-r14-binding.zip"
BASE_MANIFEST = "scripts/vnext_agent/dist/r14/gipuzkoa360-r14-binding-manifest.json"
OUT = ROOT / "scripts/vnext_agent/dist/r15"
ZIP = OUT / "gipuzkoa360-r15-final-agent.zip"
MANIFEST = OUT / "gipuzkoa360-r15-final-agent-manifest.json"
SOURCE = "agentes/gipuzkoa360_vnext/tools.py"
# Only W2 boundary validation and public metadata; no v4/provider/formula transplant.
ALLOWED_FUNCTIONS = {"_validate_arguments", "_effective_request", "_mobility_catalog_view", "_public_result"}


def sha(data):
    return hashlib.sha256(data).hexdigest()


def blob(path):
    return subprocess.check_output(["git", "show", f"{BASE}:{path}"], cwd=ROOT)


def functions(source):
    return {node.name: node for node in ast.parse(source).body if isinstance(node, ast.FunctionDef)}


def generated_tools(frozen):
    """Replace changed W2 definitions only, preserving all other generated bytes."""
    old_source = blob(SOURCE).decode("utf-8")
    source = (ROOT / SOURCE).read_text(encoding="utf-8")
    old, new = functions(old_source), functions(source)
    if old.keys() != new.keys():
        raise ValueError("Unexpected W2 function inventory change")
    changed = {name for name in old if ast.dump(old[name]) != ast.dump(new[name])}
    if not changed <= ALLOWED_FUNCTIONS:
        raise ValueError(f"Unreviewed runtime changes: {changed - ALLOWED_FUNCTIONS}")
    # Check nonfunction statements too: imported engine/config must stay intact.
    outside = lambda text: [ast.dump(n) for n in ast.parse(text).body if not isinstance(n, ast.FunctionDef)]
    if outside(old_source) != outside(source):
        raise ValueError("Unexpected nonfunction runtime change")
    text = frozen.decode("utf-8")
    nodes = functions(text)
    lines = text.splitlines(keepends=True)
    for name in sorted(changed, key=lambda name: nodes[name].lineno, reverse=True):
        node = nodes[name]
        if ast.dump(node) != ast.dump(old[name]):
            raise ValueError(f"Frozen generated function differs from R14 source: {name}")
        lines[node.lineno - 1:node.end_lineno] = [ast.unparse(new[name]) + "\n"]
    output = "".join(lines).encode("utf-8")
    ast.parse(output)
    return output, sorted(changed)


def build():
    if sys.version_info[:2] != (3, 12):
        raise RuntimeError("Canonical R15 compression requires CPython 3.12")
    baseline = blob(BASE_ZIP)
    baseline_manifest = blob(BASE_MANIFEST)
    assert sha(baseline) == "9c6fa5c692df178afe36366c6291e7c0e7c3da06134381b09d853f55d6707252"
    assert sha(baseline_manifest) == "d6c0122b475284c468fdfc3e343b9ab0d9d175cf20513048c915281cedf4e911"
    report = json.loads(baseline_manifest)
    source = (ROOT / "agentes/gipuzkoa360_vnext/main.py").read_text(encoding="utf-8")
    boundary = "try:\n    from . import tools as evidence\nexcept ImportError:\n    import tools as evidence"
    assert source.count(boundary) == 1
    main = source.replace(boundary, "import tools as evidence").encode("utf-8")
    constants = {n.targets[0].id: ast.literal_eval(n.value) for n in ast.parse(main).body
                 if isinstance(n, ast.Assign) and isinstance(n.targets[0], ast.Name)
                 and n.targets[0].id in {"SYSTEM_PROMPT", "STUDIO_CONTEXT_FILES", "AGENT_NAME"}}
    assert constants["STUDIO_CONTEXT_FILES"] == report["context_paths"]
    assert 10 <= len(constants["SYSTEM_PROMPT"]) <= 8000
    OUT.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(io.BytesIO(baseline)) as old, zipfile.ZipFile(ZIP, "w") as new:
        tool_source, changed_functions = generated_tools(old.read("tools.py"))
        overrides = {"main.py": main, "tools.py": tool_source}
        members, differences = {}, []
        for info in old.infolist():
            before = old.read(info.filename)
            data = overrides.get(info.filename, before)
            new.writestr(info, data, compress_type=zipfile.ZIP_DEFLATED, compresslevel=9)
            members[info.filename] = {"bytes": len(data), "sha256": sha(data)}
            differences.append({"path": info.filename, "changed": before != data,
                                "r14_sha256": sha(before), "r15_sha256": sha(data)})
    portal = ROOT / "agentes/gipuzkoa360_vnext/portal"
    for name, data in overrides.items():
        (portal / name).write_bytes(data)
    # Preserve R14 metadata as provenance, not as the current public contract.
    report = {k: v for k, v in report.items() if not k.startswith("r14_")}
    report.update(package="GIPUZKOA360_R15_final_agent", base_sha=BASE,
                  base_zip_sha256=sha(baseline), base_manifest_sha256=sha(baseline_manifest),
                  sha256=sha(ZIP.read_bytes()), bytes=ZIP.stat().st_size, members=members,
                  instruction_chars=len(constants["SYSTEM_PROMPT"]),
                  agent_name_chars=len(constants["AGENT_NAME"]),
                  uncompressed_bytes=sum(item["bytes"] for item in members.values()),
                  changed_members=[r["path"] for r in differences if r["changed"]],
                  member_diff_vs_r14=differences, changed_w2_functions=changed_functions,
                  public_agent_contract="R15: nine tools; plan_visit five required flat fields; comparisons by individual calls",
                  engine_contract="Unchanged W1 0.3.1 + explicit legacy 0.2.0, internal optional parameters and batch",
                  historical_audit_tests="R14/Patch3 audit-only test bytes and proof index retained; current R15 regressions off-package",
                  runtime_source_sha256={p: sha((ROOT/p).read_bytes().replace(b'\r\n', b'\n')) for p in [SOURCE, "agentes/gipuzkoa360_vnext/main.py"]})
    assert report["changed_members"] == ["main.py", "tools.py"]
    assert report["bytes"] < report["limit_bytes"]
    MANIFEST.write_text(json.dumps(report, ensure_ascii=False, sort_keys=True, indent=2) + "\n", encoding="utf-8", newline="\n")
    return {"zip_sha256": report["sha256"], "manifest_sha256": sha(MANIFEST.read_bytes()),
            "bytes": report["bytes"], "main_sha256": sha(main), "tools_sha256": sha(tool_source)}


if __name__ == "__main__":
    print(json.dumps(build(), sort_keys=True))
