// Reuse the established visual style; display recorded core outputs without recomputing metrics.
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const data=JSON.parse(fs.readFileSync(path.join(root,'analisis/jury_visual_data.json'),'utf8'));
const css=fs.readFileSync(path.join(root,'scripts/build_results.mjs'),'utf8').match(/<style>([\s\S]*?)<\/style>/)[1];
const runtime=fs.readFileSync(path.join(root,'scripts/jury_view.js'),'utf8');
const safe=JSON.stringify(data).replace(/</g,'\\u003c');
const html=`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GIPUZKOA 360 · Envejecimiento y proximidad</title><style>${css}
.case-button{padding:12px;border:1px solid #9cb7b9;border-radius:8px;background:white;cursor:pointer}.case-button[aria-pressed=true]{background:#103747;color:white}.map svg{width:100%;max-height:510px}.map{display:block}details{margin-top:16px}summary{cursor:pointer;font-weight:700}.highlight{color:#876013}#selected{min-height:3em}.metric-row{grid-template-columns:repeat(4,1fr)}@media(max-width:650px){.metric-row{grid-template-columns:1fr 1fr}}[hidden]{display:none!important}
</style></head><body><header><div class="brand">GIPUZKOA 360<small>DeustoAI Labs · Análisis territorial trazable</small></div><nav><a href="#hallazgo">Hallazgo</a><a href="#territorio">Mapa</a><a href="#scenario">Escenario</a><a href="#fuentes">Fuentes</a></nav></header>
<div class="banner" style="background:#0f5b61">Resultados reales guardados · cálculo local reproducible · esta página no es una conversación en vivo</div>
<main><div class="eyebrow">88 municipios · 148 registros sanitarios</div><h1>¿Dónde coinciden envejecimiento<br>y mayor distancia a atención primaria?</h1><p class="lead">Tres consultas al mismo agente, con criterios explícitos. Explora el resultado; contrasta la fuente antes de interpretar.</p>
<section class="card"><h2>Elige una consulta calculada</h2><div class="controls" id="cases"></div><p class="subtle">Cada opción corresponde a una ejecución local independiente. El umbral en km clasifica proximidad; los dos cortes por cuantil determinan los municipios destacados.</p></section>
<section id="hallazgo" class="card" style="margin-top:18px" aria-live="polite"><h2 id="answer"></h2><p id="names"></p><div id="kpis" class="metric-row"></div><p id="method" class="subtle"></p></section>
<div class="grid" style="margin-top:18px"><section id="territorio" class="card"><h2>Gipuzkoa, municipio a municipio</h2><div id="map" class="map"></div><p class="legend">Ocre: cumple ambos cortes · gris: resto de municipios · norte arriba</p><p id="selected" aria-live="polite">Selecciona un municipio con el ratón o el teclado.</p><p class="subtle">Contornos oficiales simplificados; representación local con corrección de longitud a 43°N. La distancia analítica se calcula en EPSG:25830, no sobre este dibujo.</p></section>
<section class="card"><h2>Municipios destacados</h2><div class="table-wrap"><table><thead><tr><th>Municipio</th><th id="age-label">65+</th><th>Distancia (m)</th></tr></thead><tbody id="rows"></tbody></table></div><div class="notice" style="margin-top:16px">La coincidencia describe estos indicadores: no demuestra causalidad ni necesidad individual. Distancia geométrica no equivale a tiempo de viaje, capacidad o citas.</div><details><summary>Ver los 88 municipios y la traza</summary><div class="table-wrap"><table><thead><tr><th>Municipio</th><th>% del grupo</th><th>Distancia (m)</th><th>Destacado</th></tr></thead><tbody id="all-rows"></tbody></table></div><pre id="trace" class="trace"></pre></details></section>
<section id="scenario" class="card wide"><span class="tag hyp">ESCENARIO HIPOTÉTICO</span><h2 style="margin-top:12px">Un nuevo registro en el punto representativo de Aduna</h2><p>Recalculado con la herramienta de escenarios, manteniendo los demás datos constantes.</p><div class="scenario-grid" id="scenario-values"></div><p class="notice">El cero corresponde a situar el nuevo punto en el punto de cálculo municipal. No significa que todos los vecinos vivan allí ni predice un efecto sanitario. Cero registros internos tampoco significa ausencia de médicos o atención.</p></section>
<section id="fuentes" class="card wide"><h2>Fuentes, periodos y alcance</h2><div id="source-list"></div><p class="notice">Las referencias no son simultáneas. El punto municipal no está ponderado por población; el grupo 75+ se deriva de nacidos hasta 1949. Una persona debe revisar la interpretación y cualquier decisión.</p></section></div>
<p class="foot">Reproducir: scripts/release/build_jury_data.py → scripts/build_jury.mjs. Evidencia y guía: docs/VALIDATION.md · docs/DEMO.md. Versión de datos fija, sin consultas de red.</p></main><script id="jury-data" type="application/json">${safe}</script><script>${runtime}</script></body></html>`;
fs.writeFileSync(path.join(root,'resultados/demo.html'),html,'utf8');
console.log('HERO resultados/demo.html; 3 recorded real cases; 88 geometries.');
