/* Presentation only: all analytical numbers and selections come from saved tools. */
const jury=JSON.parse(document.getElementById('jury-data').textContent);
const product=JSON.parse(document.getElementById('product-data').textContent);
const el=id=>document.getElementById(id);
const number=(v,d=1)=>v===null||v===undefined?'Sin dato':new Intl.NumberFormat('es-ES',{minimumFractionDigits:d,maximumFractionDigits:d,useGrouping:true}).format(v);
const metres=v=>number(v)+' m',percent=(v,d=3)=>number(v,d)+' %';
const sorted=rows=>[...rows].sort((a,b)=>a.municipality_name.localeCompare(b.municipality_name,'es'));
const caseNames={main:'Pregunta inicial · 65+',followup:'Seguimiento · 75+',strict:'Criterio más exigente · 65+',comparison:'Comparación territorial',donostia:'Verificación de Donostia',aduna:'Registros en Aduna',eibar:'Salud mental en Eibar',scenario:'Escenario hipotético',source:'Fuente demográfica',missing:'Municipio desconocido',category_error:'Categoría no cargada',source_error:'Fuente no cargada',period_error:'Periodo no soportado'};
const operations=[['obtener_resumen_territorial','Resumen territorial','¿Qué población e indicadores tiene Aduna?'],['comparar_municipios','Comparación','¿En qué difieren Eibar y Tolosa?'],['analizar_envejecimiento','Envejecimiento','¿Qué proporción tiene 65 o más años?'],['analizar_acceso_servicios','Distancia a registros','¿A qué distancia geométrica está el registro más cercano?'],['analizar_coincidencia','Coincidencia','¿Dónde se alcanzan los dos cortes?'],['simular_escenario','Escenario hipotético','¿Qué cambia al añadir o retirar un registro?'],['consultar_fuente','Fuentes','¿De dónde sale esta cifra y qué limita su uso?']];
const operationNames=Object.fromEntries(operations.map(x=>[x[0],x[1]]));
const sourceNames={EUSTAT_EMH_2025:'Eustat · 2025',GEOEUSKADI_MUNICIPIOS_2025:'geoEuskadi · 2025',ODE_HEALTH_CENTRES_2026:'Open Data Euskadi · 2026',G360_DERIVED_MUNICIPAL_METRICS_V1:'Indicadores derivados de las fuentes oficiales'};
function rows(id,values){el(id).replaceChildren();for(const cells of values){const tr=document.createElement('tr');cells.forEach((value,i)=>{const cell=document.createElement(i?'td':'th');if(!i)cell.scope='row';cell.textContent=value;tr.append(cell)});el(id).append(tr)}}
function metric(label,value,description=''){const box=document.createElement('div');box.className='metric';const h=document.createElement('h3'),strong=document.createElement('strong'),p=document.createElement('span');h.textContent=label;strong.textContent=value;p.textContent=description;box.append(h,strong,p);return box}
for(const [,name,question] of operations){const box=document.createElement('div');box.className='operation';const h=document.createElement('h3'),p=document.createElement('p');h.textContent=name;p.textContent=question;box.append(h,p);el('operations').append(box)}
for(const [id,name] of Object.entries(caseNames)){const o=document.createElement('option');o.value=id;o.textContent=name;el('trace-case').append(o)}
function trace(id){const c=product.calls[id],out=c.output;el('trace-case').value=id;el('trace-question').textContent=c.question;el('trace-human').replaceChildren();const args=c.arguments;const humanArgs=Object.entries(args).map(([key,value])=>({categoria_servicio:'Categoría',grupo_edad:'Grupo de edad',umbral_km:'Umbral (km)',periodo:'Periodo solicitado',cuantil:'Cuantil',municipio:'Municipio',municipios:'Municipios',accion:'Cambio',latitud:'Latitud',longitud:'Longitud',source_id:'Fuente'}[key]||key)+': '+(value==='primary_care'?'atención primaria':value==='add_service'?'añadir un registro':Array.isArray(value)?value.join(', '):typeof value==='number'?(Number.isInteger(value)?number(value,0):number(value,7).replace(/0+$/,'').replace(/,$/,'')):value)).join(' · ');
 const fields=[['Operación',operationNames[c.tool]||c.tool],['Herramienta',c.tool],['Parámetros',humanArgs],['Periodo',out.period||(args.periodo?args.periodo+' (solicitado; sin resultado)':'No aplica a esta salida')],['Unidad',out.unit||'No aplica a un error controlado'],['Filas usadas',out.rows_used===undefined?'No hay resultado numérico':number(out.rows_used,0)+' filas; no equivale necesariamente a municipios'],['Fuentes',(out.sources||[]).map(s=>sourceNames[s.source_id]||s.source_id).join('; ')||'Sin atribución de cifras'],['Contexto de los indicadores','Población: Eustat 2025; geometría: geoEuskadi 2025; registros: Open Data Euskadi 2026. La lista anterior conserva las fuentes declaradas por esta salida.'],['Método',out.method||'La herramienta rechazó la consulta sin fabricar un resultado.'],['Límites',(out.limitations||[]).join(' ')||'No interpretar ausencia de resultado como valor cero.']];
 for(const [name,value] of fields){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=name;dd.textContent=value;el('trace-human').append(dt,dd)}el('trace').textContent=JSON.stringify({tool:c.tool,arguments:c.arguments,output:c.output,output_sha256:c.output_sha256},null,2);
}
el('trace-case').addEventListener('change',e=>trace(e.target.value));
el('manifest').textContent=JSON.stringify({base_sha:product.base_sha,runtime_sha:product.runtime_sha,execution:product.execution,input_sha256:product.input_sha256},null,2);
let activeCase=0;
for(const r of sorted(jury.cases[0].output.data)){const o=document.createElement('option');o.value=r.municipality_code;o.textContent=r.municipality_name;el('municipality').append(o)}el('municipality').value='20051';
function selectMunicipality(){const c=jury.cases[activeCase],r=c.output.data.find(r=>r.municipality_code===el('municipality').value);if(!r){el('selected').textContent='Sin dato para este municipio; no se sustituye por cero.';return}el('selected').textContent=r.municipality_name+' · '+percent(r['pct_'+c.age_group+'_plus'])+' de población '+c.age_group+'+ · '+metres(r.nearest_distance_m)+' · '+(r.highlighted?'Cumple ambos cortes.':'No cumple ambos cortes.');el('map').querySelectorAll('path[data-code]').forEach(p=>{p.setAttribute('stroke',p.dataset.code===r.municipality_code?'#173b43':'#667d75');p.setAttribute('stroke-width',p.dataset.code===r.municipality_code?'2.5':'.6')})}
el('municipality').addEventListener('change',selectMunicipality);
function drawMap(out){const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 600 470');svg.setAttribute('role','img');svg.setAttribute('aria-labelledby','map-title map-desc');const title=document.createElementNS(ns,'title'),desc=document.createElementNS(ns,'desc');title.id='map-title';title.textContent='Coincidencia territorial en los 88 municipios de Gipuzkoa';desc.id='map-desc';desc.textContent='Los municipios rayados cumplen ambos cortes. La tabla y el selector ofrecen una alternativa textual. No representa rutas, tiempos ni prioridades de inversión.';svg.append(title,desc);const defs=document.createElementNS(ns,'defs');defs.innerHTML='<pattern id="highlight-pattern" width="7" height="7" patternUnits="userSpaceOnUse" patternTransform="rotate(35)"><rect width="7" height="7" fill="#146457"/><path d="M0 0V7" stroke="#bbd1b8" stroke-width="2"/></pattern>';svg.append(defs);
 const rings=f=>f.geometry.type==='Polygon'?f.geometry.coordinates:f.geometry.coordinates.flat();const cosine=Math.cos(43*Math.PI/180),points=jury.geometry.features.flatMap(f=>rings(f).flat()),xs=points.map(p=>p[0]*cosine),ys=points.map(p=>p[1]);const minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),scale=Math.min(560/(maxX-minX),430/(maxY-minY));const project=p=>[20+(p[0]*cosine-minX)*scale,450-(p[1]-minY)*scale];
 for(const f of jury.geometry.features){const code=String(f.properties.municipality_code),r=out.data.find(r=>r.municipality_code===code);if(!r)throw Error('Geometría sin resultado');const p=document.createElementNS(ns,'path');p.setAttribute('d',rings(f).map(ring=>ring.map((v,i)=>{const a=project(v);return(i?'L':'M')+a[0].toFixed(2)+' '+a[1].toFixed(2)}).join(' ')+' Z').join(' '));p.setAttribute('fill',r.highlighted?'url(#highlight-pattern)':'#e0e8e1');p.setAttribute('fill-rule','evenodd');p.setAttribute('stroke','#667d75');p.setAttribute('stroke-width','.6');p.dataset.code=code;const t=document.createElementNS(ns,'title');t.textContent=r.municipality_name+(r.highlighted?': cumple ambos cortes':': no cumple ambos cortes');p.append(t);p.addEventListener('click',()=>{el('municipality').value=code;selectMunicipality()});svg.append(p)}el('map').replaceChildren(svg)}
function drawCase(index){activeCase=index;const c=jury.cases[index],out=c.output,age='pct_'+c.age_group+'_plus';document.querySelectorAll('.case-button').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===index)));el('answer').textContent=number(c.highlighted_count,0)+' / '+number(out.rows_used,0);el('cuts').textContent=c.age_group+'+ ≥ '+percent(c.age_cut_percent,4)+' · distancia ≥ '+metres(c.distance_cut_m);el('answer-mobile').textContent=el('answer').textContent;el('cuts-mobile').textContent=el('cuts').textContent;el('table-caption').textContent='Cuantil '+number(c.quantile,2)+' · atención primaria';el('age-label').textContent=c.age_group+'+ (%)';el('threshold-label').textContent='Dentro de '+number(c.threshold_km,0)+' km';el('method').textContent=out.method;el('exact-method').textContent=out.method;el('limits').replaceChildren();[...(out.warnings||[]),...(out.limitations||[])].forEach(value=>{const li=document.createElement('li');li.textContent=value;el('limits').append(li)});rows('rows',sorted(out.data.filter(r=>r.highlighted)).map(r=>[r.municipality_name,percent(r[age]),metres(r.nearest_distance_m),r.within_threshold?'Sí':'No']));drawMap(out);selectMunicipality();trace(['main','followup','strict'][index])}
jury.cases.forEach((c,i)=>{const b=document.createElement('button');b.className='case-button';b.type='button';b.textContent=c.age_group+'+ · cuantil '+number(c.quantile,2)+' · '+number(c.threshold_km,0)+' km';b.addEventListener('click',()=>drawCase(i));el('cases').append(b);el('sensitivity').append(metric(c.age_group+'+ · cuantil '+number(c.quantile,2),number(c.highlighted_count,0)+' municipios','Cortes: '+percent(c.age_cut_percent,4)+' y '+metres(c.distance_cut_m))) });
const d=product.calls.donostia.output.data[0];el('donostia').append(metric('Población total',number(d.population_total,0),'personas'),metric('Personas de 65 o más',number(d.population_65_plus,0),'personas'),metric('Proporción de 65+',percent(d.pct_65_plus),'sobre el total municipal'));el('verification').textContent=number(d.population_65_plus,0)+' ÷ '+number(d.population_total,0)+' × 100 = '+percent(d.pct_65_plus)+'. Eustat · 01/01/2025. Ambos recuentos se contrastan con el CSV oficial conservado.';
rows('comparison',jury.control_comparison.data.map(r=>[r.municipality_name,number(r.population_total,0),percent(r.pct_75_plus),metres(r.nearest_distance_m)]));
const a=product.calls.aduna.output.data[0].service_indicators.primary_care,e=product.calls.eibar.output.data[0].service_indicators.mental_health;
el('edge-cases').append(metric('Aduna · atención primaria',number(a.registered_service_count,0)+' registros internos','El más cercano está a '+metres(a.nearest_distance_m)+'. Cero registros no significa cero médicos ni ausencia de atención.'),metric('Eibar · salud mental',number(e.registered_service_count,0)+' registro',metres(e.nearest_distance_m)+'. Tasas: '+number(e.rate_per_10000_65_plus,3)+' por 10.000 personas de 65+ y '+number(e.rate_per_10000_75_plus,3)+' por 10.000 de 75+. No es capacidad.'));
const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('es');function search(){const term=normalize(el('search').value.trim()),filtered=sorted(jury.cases[0].output.data).filter(r=>normalize(r.municipality_name).includes(term));rows('all-rows',filtered.map(r=>[r.municipality_name,percent(r.pct_65_plus),metres(r.nearest_distance_m),r.highlighted?'Sí':'No']));el('search-status').textContent=filtered.length?filtered.length+' municipios visibles de 88.':'Sin coincidencias con este nombre en la salida guardada. No significa cero población ni cero servicios.';el('search-status').className=filtered.length?'caption':'empty'}el('search').addEventListener('input',search);search();
const scenario=product.calls.scenario.output,aduna=scenario.data.find(r=>r.municipality_name==='Aduna'),sa=product.calls.scenario.arguments;
el('scenario-change').textContent='CAMBIO: añadir un registro hipotético de atención primaria en '+number(sa.latitud,7)+'; '+number(sa.longitud,7)+' (latitud, longitud).';el('scenario-values').append(metric('BASE',metres(aduna.baseline_distance_m),'registro existente más cercano'),metric('RESULTADO RECALCULADO',metres(aduna.scenario_distance_m),'con el registro hipotético añadido'),metric('DIFERENCIA',metres(aduna.difference_absolute_m),'escenario menos base'));rows('scenario-rows',sorted(scenario.data).map(r=>[r.municipality_name,metres(r.baseline_distance_m),metres(r.scenario_distance_m),metres(r.difference_absolute_m)]));el('scenario-count').textContent=scenario.summary.affected_rows+' municipios con cambio de '+scenario.summary.total_result_rows+' evaluados. '+scenario.rows_used+' filas usadas de entrada, que no equivalen a municipios afectados.';
for(const id of ['EUSTAT_EMH_2025','GEOEUSKADI_MUNICIPIOS_2025','ODE_HEALTH_CENTRES_2026']){const s=product.sources.find(s=>s.source_id===id),div=document.createElement('div'),h=document.createElement('h3'),p=document.createElement('p'),a=document.createElement('a'),details=document.createElement('details'),summary=document.createElement('summary'),more=document.createElement('p');h.textContent=sourceNames[id];p.textContent=s.title+' · '+s.reference_period;a.href=s.url;a.textContent='Consultar fuente original';a.target='_blank';a.rel='noopener';summary.textContent='Ficha, transformación y límites';more.textContent=s.institution+' · '+s.unit+' · '+s.license+'. '+s.method+' '+s.limitations.join(' ')+' Identificador: '+s.source_id;details.append(summary,more);div.append(h,p,a,details);el('source-list').append(div)}
const inv=product.inventory,v=product.validation;
el('inventory').append(metric('Municipios',number(inv.municipalities,0),'unidades del catálogo preparado'),metric('Registros sanitarios',number(inv.health_records,0),'registros públicos; no capacidad asistencial'),metric('Operaciones',number(inv.tools.length,0),'herramientas públicas del agente'));
el('benchmark-context').textContent='Evidencia conservada del '+v.generated_at.slice(0,10)+'. Benchmark sobre candidato '+v.candidate_sha.slice(0,7)+'. Los tests Python/Node siguientes corresponden a la base de integración documentada, no al recuento actualizado de esta rama.';
el('validation-kpis').append(metric('Checks del benchmark',number(v.checks.passed,0)+' / '+number(v.checks.total,0),'evaluaciones de sujeto × propiedad'),metric('Salidas numéricas trazables',number(v.traceability.numerator,0)+' / '+number(v.traceability.denominator,0),'outputs auditados en el benchmark definido'),metric('Corrupciones controladas',number(v.fault_injection.controlled_rejection,0)+' / '+number(v.fault_injection.total,0),'inyecciones deliberadas rechazadas'),metric('Prueba sostenida',number(v.soak.calls,0)+' llamadas',number(v.soak.result_drift,0)+' derivas; '+v.soak.exceptions.length+' excepciones observadas'),metric('Tests Python · base',v.baseline_tests.python.join(' / '),'pruebas de la integración documentada'),metric('Tests Node · base',v.baseline_tests.node.join(' / '),'pruebas de contrato e integración'),metric('Critical abiertos',number(v.open_by_severity.Critical,0),'hallazgos conocidos del benchmark'),metric('High abiertos',number(v.open_by_severity.High,0),'hallazgos conocidos del benchmark'),metric('Medium abiertos',number(v.open_by_severity.Medium,0),'salida extrema no demostrada en portal'));
const kpis=[['Municipios: unidades distintas del catálogo',inv.municipalities+' / '+inv.municipalities,'datos_preparados/municipios.csv','No representa personas ni validación de usuarios'],['Registros sanitarios: filas del catálogo público',inv.health_records+' / '+inv.health_records,'datos_preparados/runtime_servicios.csv','No mide centros únicos por edificio, personal, capacidad o citas'],['Tools: operaciones públicas declaradas',inv.tools.length+' / '+inv.tools.length,'agentes/gipuzkoa360/portal/main.py','No son agentes independientes ni llamadas en directo'],['Checks: sujeto × propiedad evaluada',v.checks.passed+' / '+v.checks.total,v.source+' → checks','No son conversaciones ni todas las entradas posibles'],['Trazabilidad: periodo, unidad, método y source_id resoluble',v.traceability.numerator+' / '+v.traceability.denominator,v.source+' → traceability','Solo outputs analíticos exitosos con números en data; no todas las respuestas posibles'],['Inyecciones: corrupción deliberada rechazada',v.fault_injection.controlled_rejection+' / '+v.fault_injection.total,v.source+' → fault_injection','No cubre todas las corrupciones posibles'],['Soak: llamadas sin excepción en la prueba sostenida',(v.soak.calls-v.soak.exceptions.length)+' / '+v.soak.calls,v.source+' → soak','Sin deriva en esa secuencia; no garantiza funcionamiento indefinido'],['Python / Node: tests aprobados de la base',v.baseline_tests.python.join('/')+'; '+v.baseline_tests.node.join('/'),v.baseline_tests.source,'No equivale a sesiones del portal ni incluye nuevos tests de esta rama'],['Critical / High / Medium: hallazgos abiertos por severidad',v.open_by_severity.Critical+'; '+v.open_by_severity.High+'; '+v.open_by_severity.Medium+' / no aplica (recuento)',v.source+' → open_by_severity','Ausencia de hallazgos conocidos en esa evaluación; no riesgo cero']];rows('kpi-definitions',kpis);
el('known-risk').textContent='Riesgo conocido: '+number(v.issues[0].payload_chars,0)+' caracteres. '+v.issues[0].reason+' Su ejecución en el portal no está demostrada. Se conserva la evidencia completa.';
drawCase(0);if(document.body.dataset.mode==='scenario')trace('scenario');if(document.body.dataset.mode==='report')trace('donostia');

function setMethodFor(output){el('exact-method').textContent=output.method;el('limits').replaceChildren();[...(output.warnings||[]),...(output.limitations||[])].forEach(value=>{const li=document.createElement('li');li.textContent=value;el('limits').append(li)});}
if(document.body.dataset.mode==='scenario')setMethodFor(scenario);
if(document.body.dataset.mode==='report')setMethodFor(product.calls.donostia.output);

window.addEventListener('pageshow',search);
if(product.next_prototype){el('prototype-section').hidden=false;const p=product.next_prototype,a=document.createElement('a');a.href='https://github.com/Asier-Comba/Guipuzkoa360/blob/'+p.snapshot_commit+'/'+p.snapshot_path;a.textContent='Snapshot final publicado del prototipo';a.target='_blank';a.rel='noopener';el('prototype-source').append(a,document.createTextNode(' · snapshot '+p.snapshot_commit.slice(0,7)+'; evidencia '+p.source_commit.slice(0,7)+'. Reconciliado con el handoff técnico final; sigue siendo offline y no está activo en el portal.'));}
